services:
  ollama-pull-service:
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - ./ollama/ollama:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh
    container_name: ollama-pull
    entrypoint: ["/bin/bash", "/entrypoint.sh"]

  vector-store-service:
    build:
      context: .
      args:
        FAISS_VERSION: cpu  # Especifique 'gpu' se necessário
    container_name: vector-store-container
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - ollama-pull-service
    command: python test/test.py"

networks:
  default:
    driver: bridge
