services:
  vector-store-service:
    build:
      context: .
      args:
        FAISS_VERSION: cpu  # 'cpu' or 'gpu'
    container_name: myveccontainer
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    command: python src/vector_store_iphan-obs.py
