version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama-server
    expose:
      - 11434/tcp
    ports:
      - 11434:11434
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:11434" ]
      interval: 60s
      timeout: 30s
      retries: 10
    volumes:
      - ./ollama/ollama:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: ["/bin/bash", "/entrypoint.sh" ]
    networks:
      - ollama-network

  vector-store:
    image: python:3.12.6
    container_name: python_app
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "
      pip install faiss-cpu &&
      pip install --no-cache-dir -r requirements.txt &&
      cd test &&
      python test.py
      "
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      ollama:
        condition: service_healthy
    networks:
      - ollama-network

networks:
  ollama-network:
    driver: bridge