services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama-server
    expose:
      - 11434/tcp
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:11434" ]
      interval: 60s
      timeout: 30s
      retries: 10
    volumes:
      - ./ollama/ollama:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: ["/bin/bash", "/entrypoint.sh" ]
    networks:
      - ollama-network

  vector-store:
    image: python:3.12.6
    container_name: routine-vector-store
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "
      pip install --no-cache-dir -r requirements_vector_store.txt &&
      cd src &&
      python vector_store_iphan_obs.py
      "
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      ollama:
        condition: service_healthy
    networks:
      - ollama-network

  chatbot:
    image: python:3.12.6
    container_name: chatbot-api
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "
      pip install --no-cache-dir -r requirements_api.txt &&
      cd src &&
      python chatbot_api.py
      "
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      ollama:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - ollama-network

  mysql:
    image: mysql:latest
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dbwordpress
      MYSQL_USER: user_leitura
      MYSQL_PASSWORD: senha@123
    ports:
      - "3306:3306"
    volumes:
      - C:\Users\Tathiana\Documents\DOCKER_MYSQL_VOLUME:/var/lib/mysql
    networks:
      - ollama-network


networks:
  ollama-network:
    driver: bridge